version: '3'
services:
  web:
    image: node:14 # Use the Node.js 14 image
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000" # Map port 3000 on host to port 3000 in container
    command: npm run start
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: BasicDBnew
      POSTGRES_USER: dipin
      POSTGRES_PASSWORD: 1234
      
    ports:
      - "5432:5432" # Map port 5432 on host to port 5432 in container
